version: '3.8'

services:
  # 1. Serviço de Banco de Dados PostgreSQL
  db:
    image: postgres:14
    container_name: nimble_db
    restart: always
    environment:
      POSTGRES_DB: nimble_gateway_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1998
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - nimble-network

    # Adicionando HEALTHCHECK: ESSENCIAL para garantir que o banco de dados está pronto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # Tempo de espera para começar a checar

  # 2. Serviço da Aplicação Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nimble_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nimble_gateway_test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1998
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: public

      # Outras variáveis de ambiente
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: sQf9n1R0v8k3tF2mY6WzXQ9uA4dJpOeR2bVhK3L1T0M=POWDPoONOIoijNKlknoi
      APP_AUTHORIZER_MOCK_MODE: "true"

    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - nimble-network

    # Usando depends_on + condition: service_healthy: A SOLUÇÃO para o seu erro
    depends_on:
      db:
        condition: service_healthy

# Definição de Volumes
volumes:
  db-data:
    driver: local

# Definição de Redes (Melhor Prática)
networks:
  nimble-network:
    driver: bridge