server:
  port: 8080
  servlet:
    context-path: /nimble-gateway

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nimble_gateway_test
    username: postgres
    password: 1998
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    jwt:
      secret: sQf9n1R0v8k3tF2mY6WzXQ9uA4dJpOeR2bVhK3L1T0M=POWDPoONOIoijNKlknoi

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  info:
    title: Nimble Gateway API
    description: API de gateway de pagamentos — desafio técnico Nimble.
    version: 1.0.0
